# To debug, it's recommended you modify / use the version in the test-actions repo:
# https://github.com/covid-projections/test-actions/blob/master/.github/workflows/deploy_api.yml

name: Build & Publish API artifacts to data.covidactnow.org

on:
  # covid-data-public fetches data at 00:00 and 12:00 UTC.
  # So we rebuild / publish the API at 00:30 and 12:30 UTC.
  schedule:
   - cron: '30 0,12 * * *'

  push:
  # Hook to trigger a manual run.
  # See: https://goobar.io/2019/12/07/manually-trigger-a-github-actions-workflow/
  repository_dispatch:
    types: publish-api

jobs:
  execute-model:
    runs-on: self-hosted
    # strategy:
    #   max-parallel: 25
    #   matrix:
    #     us-states: ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']

    env:
      # To pin to an old data set or model code, put the branch/tag/commit here:
      COVID_DATA_PUBLIC_REF: 'master'
      # !!! Change this to your BRANCH if you want to test it
      COVID_DATA_MODEL_REF: 'fridiculous/parallelize-via-github'
      SNAPSHOT_ID: ${{github.run_number}}
      # FOR_US_STATE: ${{ matrix.us-states }}
    steps:
    - name: Checkout covid-data-model
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-model
        path: covid-data-model
        ref: '${{env.COVID_DATA_MODEL_REF}}'
    - name: Checkout covid-data-public
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-public
        path: covid-data-public
        lfs: true
        ref: '${{env.COVID_DATA_PUBLIC_REF}}'
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.6'
        architecture: 'x64'
    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Dependencies
      working-directory: ./covid-data-model
      run: pip install -r requirements.txt

    # - name: create temp file
    #   run: |
    #     mkdir -p /data/api-results-${{env.SNAPSHOT_ID}}
    #     touch /data/api-results-${{env.SNAPSHOT_ID}}/deleteme
    - name: Build Model Results (run.sh .. .. execute_model)
      env:
        COVID_MODEL_CORES: 96
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: ./covid-data-model/run.sh ./covid-data-public /data/api-results-${{env.SNAPSHOT_ID}} execute_model
    - name: Zip Model Results (run.sh .. .. execute_zip_folder)
      run: ./covid-data-model/run.sh ./covid-data-public /data/api-results-${{env.SNAPSHOT_ID}} execute_zip_folder
    - name: Upload Model Results
      uses: actions/upload-artifact@v2-preview
      with:
        name: model-results-${{env.SNAPSHOT_ID}}
        path: /data/api-results-${{env.SNAPSHOT_ID}}/api-results.zip
        # path: /data/api-results-${{env.SNAPSHOT_ID}}/api-results-${{env.FOR_US_STATE}}.zip

  execute-summaries:
    runs-on: self-hosted
    needs: execute-model
    env:
      # To pin to an old data set or model code, put the branch/tag/commit here:
      COVID_DATA_PUBLIC_REF: 'master'
      # !!! Change this to your BRANCH if you want to test it
      COVID_DATA_MODEL_REF: 'master'
      SNAPSHOT_ID: ${{github.run_number}}
    steps:
    - name: Checkout covid-data-model
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-model
        path: covid-data-model
        ref: '${{env.COVID_DATA_MODEL_REF}}'
    - name: Checkout covid-data-public
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-public
        path: covid-data-public
        lfs: true
        ref: '${{env.COVID_DATA_PUBLIC_REF}}'
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.6'
        architecture: 'x64'
    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Dependencies
      working-directory: ./covid-data-model
      run: pip install -r requirements.txt

    - name: Build Summaries (run.sh .. .. execute_summaries)
      env:
        COVID_MODEL_CORES: 96
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: ./covid-data-model/run.sh ./covid-data-public /data/api-results-${{env.SNAPSHOT_ID}} execute_summaries

  execute-dod:
    runs-on: self-hosted
    needs: execute-model
    env:
      # To pin to an old data set or model code, put the branch/tag/commit here:
      COVID_DATA_PUBLIC_REF: 'master'
      # !!! Change this to your BRANCH if you want to test it
      COVID_DATA_MODEL_REF: 'master'
      SNAPSHOT_ID: ${{github.run_number}}
    steps:
    - name: Checkout covid-data-model
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-model
        path: covid-data-model
        ref: '${{env.COVID_DATA_MODEL_REF}}'
    - name: Checkout covid-data-public
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-public
        path: covid-data-public
        lfs: true
        ref: '${{env.COVID_DATA_PUBLIC_REF}}'
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.6'
        architecture: 'x64'
    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Dependencies
      working-directory: ./covid-data-model
      run: pip install -r requirements.txt

    - name: Build DoD (run.sh .. .. execute_summaries)
      env:
        COVID_MODEL_CORES: 96
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: ./covid-data-model/run.sh ./covid-data-public /data/api-results-${{env.SNAPSHOT_ID}} execute_dod

  execute-api:
    runs-on: self-hosted
    needs: execute-model
    env:
      # To pin to an old data set or model code, put the branch/tag/commit here:
      COVID_DATA_PUBLIC_REF: 'master'
      # !!! Change this to your BRANCH if you want to test it
      COVID_DATA_MODEL_REF: 'master'
      SNAPSHOT_ID: ${{github.run_number}}
    steps:
    - name: Checkout covid-data-model
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-model
        path: covid-data-model
        ref: '${{env.COVID_DATA_MODEL_REF}}'
    - name: Checkout covid-data-public
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-public
        path: covid-data-public
        lfs: true
        ref: '${{env.COVID_DATA_PUBLIC_REF}}'
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.6'
        architecture: 'x64'
    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Dependencies
      working-directory: ./covid-data-model
      run: pip install -r requirements.txt

    - name: Build API (run.sh .. .. execute_api)
      env:
        COVID_MODEL_CORES: 96
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: ./covid-data-model/run.sh ./covid-data-public /data/api-results-${{env.SNAPSHOT_ID}} execute_api

  # push-snapshot-to-s3:
  #   runs-on: self-hosted
  #   needs:
  #     - execute-model
  #     - execute-api
  #     - execute-dod
  #     - execute-summaries
  #   env:
  #     # To pin to an old data set or model code, put the branch/tag/commit here:
  #     COVID_DATA_PUBLIC_REF: 'master'
  #     # !!! Change this to your BRANCH if you want to test it
  #     COVID_DATA_MODEL_REF: 'master'
  #     SNAPSHOT_ID: ${{github.run_number}}
  #     AWS_S3_BUCKET: 'data.covidactnow.org'

    # steps:
    # - name: make and copy to local tmp directory
    #   run: |
    #     mkdir -p ./tmp/data/
    #     cp -r /data/api-results-${{env.SNAPSHOT_ID}}/ ./tmp/data/

    # - name: Deploy Artifacts to S3 (https://data.covidactnow.org/snapshot/${{env.SNAPSHOT_ID}}/).
    #   uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --acl public-read --follow-symlinks --delete
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     SOURCE_DIR: './tmp/data/api-results-${{env.SNAPSHOT_ID}}/'
    #     DEST_DIR: 'snapshot/${{env.SNAPSHOT_ID}}/'

    # - name: remove local tmp directory
    #   run: |
    #     rm -rf ./tmp/data/

